spring:
  config:
    import: "optional:configserver:http://config-service:10001"
    activate:
      on-profile: docker
  output:
    ansi:
      enabled: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:10000/eureka/
    healthcheck:
      enabled: true

---
spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:http://localhost:10001"
  output:
    ansi:
      enabled: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
    healthcheck:
      enabled: true